<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kwale</name>
   <tag></tag>
   <elementGuidId>b1ce002c-9c0d-417a-9a85-82555e633dfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;edit-patient-form&quot;]/div[1]/fieldset[3]/table[3]/tbody/tr[2]/td[1]/select/option[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;edit-patient-form&quot;]/div[1]/fieldset[3]/table[3]/tbody/tr[2]/td[1]/select/option[2]</value>
   </webElementProperties>
</WebElementEntity>
