<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>location</name>
   <tag></tag>
   <elementGuidId>21fb0990-55d7-43bb-a990-13ca11929df2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>personAddress.address6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>personAddress.address6</value>
   </webElementProperties>
</WebElementEntity>
