<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NearestHealthCenter</name>
   <tag></tag>
   <elementGuidId>1f9ef7bb-ee4b-4a11-993e-d0065cd45a24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name=&quot;nearestHealthFacility&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name=&quot;nearestHealthFacility&quot;]</value>
   </webElementProperties>
</WebElementEntity>
