<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NextOfKinPostalAddress</name>
   <tag></tag>
   <elementGuidId>fe88fa59-9146-48e3-9d0b-b138f23c4c6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name=&quot;nextOfKinAddress&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name=&quot;nextOfKinAddress&quot;]</value>
   </webElementProperties>
</WebElementEntity>
