<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>partner</name>
   <tag></tag>
   <elementGuidId>c9a7a961-b300-4c89-9dbc-b423a78052cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;edit-patient-form&quot;]/div[1]/fieldset[4]/table[1]/tbody/tr[2]/td[2]/select/option[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;edit-patient-form&quot;]/div[1]/fieldset[4]/table[1]/tbody/tr[2]/td[2]/select/option[2]</value>
   </webElementProperties>
</WebElementEntity>
