<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>enrollHIVButton</name>
   <tag></tag>
   <elementGuidId>3ef6bf59-9e65-4c1d-8aee-f6d4baada22e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/table/tbody/tr/td[1]/div[3]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/table/tbody/tr/td[1]/div[3]/div[2]/button</value>
   </webElementProperties>
</WebElementEntity>
