<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HTSform</name>
   <tag></tag>
   <elementGuidId>3f228dda-35d4-40df-ba84-33f12d2c512f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div[1]/table/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div[1]/table/tbody/tr/td[2]</value>
   </webElementProperties>
</WebElementEntity>
