<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>month</name>
   <tag></tag>
   <elementGuidId>d1dd7358-62a0-437d-bce8-9ee0446dbfd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ui-datepicker-div&quot;]/div[1]/div/select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ui-datepicker-div&quot;]/div[1]/div/select[1]</value>
   </webElementProperties>
</WebElementEntity>
