<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_out_button</name>
   <tag></tag>
   <elementGuidId>9c464ecd-7e8e-414f-a856-6d426b4732f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[2]/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[2]/div/button[2]</value>
   </webElementProperties>
</WebElementEntity>
