<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>County</name>
   <tag></tag>
   <elementGuidId>4482afcf-4c78-4f8d-999d-fd6c350cdea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div[2]/div/form/div[1]/fieldset[3]/table[3]/tbody/tr[2]/td[1]/select
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[2]/div/form/div[1]/fieldset[3]/table[3]/tbody/tr[2]/td[1]/select
</value>
   </webElementProperties>
</WebElementEntity>
