<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>County_Name</name>
   <tag></tag>
   <elementGuidId>34cbe9af-0a2f-4ab2-9ef6-fb19dde6d487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div[2]/div/form/div[1]/fieldset[3]/table[3]/tbody/tr[2]/td[1]/select/option[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[2]/div/form/div[1]/fieldset[3]/table[3]/tbody/tr[2]/td[1]/select/option[3]</value>
   </webElementProperties>
</WebElementEntity>
