<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drug_other</name>
   <tag></tag>
   <elementGuidId>2dc35043-4c77-471d-a1ef-3ccfc98f7669</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form[@id='new-order']/p[2]/span/select-drug/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form[@id='new-order']/p[2]/span/select-drug/input</value>
   </webElementProperties>
</WebElementEntity>
