<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drug_quantity_02</name>
   <tag></tag>
   <elementGuidId>0e396afc-65c5-4229-97af-23e9293d80c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;drug-order-group&quot;]/div[1]/table/tbody/tr[4]/td[5]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;drug-order-group&quot;]/div[1]/table/tbody/tr[4]/td[5]/input</value>
   </webElementProperties>
</WebElementEntity>
