<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drug-order</name>
   <tag></tag>
   <elementGuidId>d3e46a86-e0cf-4674-9c5d-06a46bc5f1b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/table/tbody/tr/td[3]/div/div/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/table/tbody/tr/td[3]/div/div/ul/li[6]/a</value>
   </webElementProperties>
</WebElementEntity>
