<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emptyField</name>
   <tag></tag>
   <elementGuidId>f58b628f-b192-485e-a6c5-357edc45079b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tbl-hiv-test&quot;]/tbody/tr[1]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tbl-hiv-test&quot;]/tbody/tr[1]/td[4]</value>
   </webElementProperties>
</WebElementEntity>
