<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>followup-reason</name>
   <tag></tag>
   <elementGuidId>bee4d7c5-fdc5-411b-8184-d1f8cf73a57b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div/div[1]/div/div[4]/fieldset[7]/table[1]/tbody/tr[1]/td[2]/span[3]/select/option[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div/div[1]/div/div[4]/fieldset[7]/table[1]/tbody/tr[1]/td[2]/span[3]/select/option[2]</value>
   </webElementProperties>
</WebElementEntity>
