<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GreenCard_Child_WHO</name>
   <tag></tag>
   <elementGuidId>6803c023-b8e4-43e7-9687-0e337843b9e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div/div[1]/div/div[1]/fieldset[4]/table/tbody/tr[2]/td[1]/div[2]/table/tbody/tr/td[2]/span/select/option[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div/div[1]/div/div[1]/fieldset[4]/table/tbody/tr[2]/td[1]/div[2]/table/tbody/tr/td[2]/span/select/option[4]</value>
   </webElementProperties>
</WebElementEntity>
