<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>green-card-complains</name>
   <tag></tag>
   <elementGuidId>b29d3c62-6e82-4f3b-b928-46848aa2ee30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div/div[1]/div/div[2]/fieldset[1]/table[1]/tbody/tr[2]/td[1]/span/select/option[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div/div[1]/div/div[2]/fieldset[1]/table[1]/tbody/tr[2]/td[1]/span/select/option[2]</value>
   </webElementProperties>
</WebElementEntity>
