<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>green-card-next</name>
   <tag></tag>
   <elementGuidId>7bc1f63d-5e11-4f63-b8c1-75baf95a2292</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div/div[2]/a[2]</value>
   </webElementProperties>
</WebElementEntity>
