<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hiv_regimen_start_date_field</name>
   <tag></tag>
   <elementGuidId>d8397b5b-04d8-4b52-a6f8-b7ca3dea1104</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class=&quot;hasDatepicker&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class=&quot;hasDatepicker&quot;]</value>
   </webElementProperties>
</WebElementEntity>
