<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hiv_regimen</name>
   <tag></tag>
   <elementGuidId>daec1275-decd-4e60-8fde-f05de557dd1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/fieldset/form/span[2]/div/select/optgroup[1]/option[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/fieldset/form/span[2]/div/select/optgroup[1]/option[1]</value>
   </webElementProperties>
</WebElementEntity>
