<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hiv_free_click</name>
   <tag></tag>
   <elementGuidId>41312603-2268-4921-8d7d-3928c7ad7955</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/div/form/div/div[3]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/div/form/div/div[3]/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
