<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HTS_Initial_Button</name>
   <tag></tag>
   <elementGuidId>f331b294-4501-4cb0-b7e7-25df7e8d33b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/table/tbody/tr/td[2]/div[5]/div[2]/div[1]/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/table/tbody/tr/td[2]/div[5]/div[2]/div[1]/b</value>
   </webElementProperties>
</WebElementEntity>
