<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lab_save_button_02</name>
   <tag></tag>
   <elementGuidId>98f783e6-ecaf-4c88-b73e-6281f379d4de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div/div/div/div/div[2]/div/div[9]/div/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div/div/div/div/div[2]/div/div[9]/div/div/div[3]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
