<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lab_order_reason_save</name>
   <tag></tag>
   <elementGuidId>77e6ebd0-5af5-4a71-bdb0-f201c9ef15a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div/div/div/div/div[2]/div/div[6]/div/div/div[3]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div/div/div/div/div[2]/div/div[6]/div/div/div[3]/div/button</value>
   </webElementProperties>
</WebElementEntity>
