<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>resultgivenYes</name>
   <tag></tag>
   <elementGuidId>0140a3c6-47cc-4af0-9ca1-bc8939db9b0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div[2]/fieldset[5]/table[3]/tbody/tr[3]/td[2]/span/select/option[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div[2]/fieldset[5]/table[3]/tbody/tr[3]/td[2]/span/select/option[2]</value>
   </webElementProperties>
</WebElementEntity>
