<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rlnship_kin</name>
   <tag></tag>
   <elementGuidId>47b82e68-2e05-4bb5-9bb9-186edccec4c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;edit-patient-form&quot;]/div[1]/fieldset[4]/table[1]/tbody/tr[2]/td[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;edit-patient-form&quot;]/div[1]/fieldset[4]/table[1]/tbody/tr[2]/td[2]/select</value>
   </webElementProperties>
</WebElementEntity>
