<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>standard-care</name>
   <tag></tag>
   <elementGuidId>c21e0c90-bb6d-420a-9f0c-a93bb05d59f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div/div[1]/div/div[4]/fieldset[7]/table[3]/tbody/tr[1]/td[2]/span/select/option[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div/div[1]/div/div[4]/fieldset[7]/table[3]/tbody/tr[1]/td[2]/span/select/option[2]</value>
   </webElementProperties>
</WebElementEntity>
