<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubmitRegistration</name>
   <tag></tag>
   <elementGuidId>636be6ba-8f28-4b14-8440-41403558bf7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;edit-patient-form&quot;]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;edit-patient-form&quot;]/div[2]/button</value>
   </webElementProperties>
</WebElementEntity>
