<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submit-greencard</name>
   <tag></tag>
   <elementGuidId>cbe3d4a7-dd86-411d-8335-9833df2fbea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div/div[2]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div/div[2]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
