<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Submit_alcohol_Screening</name>
   <tag></tag>
   <elementGuidId>a19646ce-8bc5-439a-9f1b-97683349c392</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[5]/div[1]/div/form/div/div[3]/div/div[3]/input</value>
   </webElementProperties>
</WebElementEntity>
