<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kp_check_in</name>
   <tag></tag>
   <elementGuidId>a4085399-62f4-491a-9135-5d9f3deaa994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='content']/div[2]/div/div[3]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[3]/div/div/button</value>
   </webElementProperties>
</WebElementEntity>
