<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kp_diagnosis-submit_button</name>
   <tag></tag>
   <elementGuidId>258f512a-cd31-4586-aa74-fd73debadf02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;htmlform&quot;]/div/div[3]/div/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;htmlform&quot;]/div/div[3]/div/div[3]/input</value>
   </webElementProperties>
</WebElementEntity>
