<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kp_enroll_button</name>
   <tag></tag>
   <elementGuidId>f4c5fd3e-b4c6-4d7d-b4c8-c91c6a6ff38b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;content&quot;]/div[2]/div/div[1]/div[4]/div[6]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;content&quot;]/div[2]/div/div[1]/div[4]/div[6]/div[2]/button</value>
   </webElementProperties>
</WebElementEntity>
