<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kp_enrollment_type</name>
   <tag></tag>
   <elementGuidId>fe7e489b-2255-4696-a4c2-b49c9bd38382</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//fieldset/table/tbody/tr/td[2]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//fieldset/table/tbody/tr/td[2]/span/input</value>
   </webElementProperties>
</WebElementEntity>
