<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PHQ9_button_form</name>
   <tag></tag>
   <elementGuidId>0b6b338e-109f-4443-bac1-c7edc659802a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;clinical-tools&quot;]/li/a/div[1]/b
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;clinical-tools&quot;]/li/a/div[1]/b
</value>
   </webElementProperties>
</WebElementEntity>
